# Generated by Django 2.2.7 on 2020-03-17 12:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('collection_management', '0002_auto_20200130_1032'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalscpombestrain',
            name='name',
        ),
        migrations.RemoveField(
            model_name='historicalscpombestrain',
            name='parental_strain',
        ),
        migrations.RemoveField(
            model_name='scpombestrain',
            name='name',
        ),
        migrations.RemoveField(
            model_name='scpombestrain',
            name='parental_strain',
        ),
        migrations.AddField(
            model_name='historicalscpombestrain',
            name='former_name',
            field=models.CharField(blank=True, max_length=32, verbose_name='former name'),
        ),
        migrations.AddField(
            model_name='historicalscpombestrain',
            name='frozen_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalscpombestrain',
            name='frozen_on',
            field=models.DateTimeField(default=None, verbose_name='frozen on'),
        ),
        migrations.AddField(
            model_name='historicalscpombestrain',
            name='genotype',
            field=models.TextField(blank=True, verbose_name='genotype'),
        ),
        migrations.AddField(
            model_name='historicalscpombestrain',
            name='made_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalscpombestrain',
            name='ploidy',
            field=models.CharField(blank=True, choices=[('haploid', 'haploid'), ('diploid', 'diploid'), ('triploid', 'triploid'), ('tetraploid', 'tetraploid')], max_length=20, verbose_name='ploidy'),
        ),
        migrations.AddField(
            model_name='historicalscpombestrain',
            name='strain_name',
            field=models.CharField(default='test', max_length=32, verbose_name='strain name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scpombestrain',
            name='former_name',
            field=models.CharField(blank=True, max_length=32, verbose_name='former name'),
        ),
        migrations.AddField(
            model_name='scpombestrain',
            name='frozen_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='frozen_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='scpombestrain',
            name='frozen_on',
            field=models.DateTimeField(default=None, verbose_name='frozen on'),
        ),
        migrations.AddField(
            model_name='scpombestrain',
            name='genotype',
            field=models.TextField(blank=True, verbose_name='genotype'),
        ),
        migrations.AddField(
            model_name='scpombestrain',
            name='made_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='made_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='scpombestrain',
            name='ploidy',
            field=models.CharField(blank=True, choices=[('haploid', 'haploid'), ('diploid', 'diploid'), ('triploid', 'triploid'), ('tetraploid', 'tetraploid')], max_length=20, verbose_name='ploidy'),
        ),
        migrations.AddField(
            model_name='scpombestrain',
            name='strain_name',
            field=models.CharField(default='test', max_length=32, verbose_name='strain name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='historicalscpombestrain',
            name='mating_type',
            field=models.CharField(blank=True, choices=[('h-', 'h-'), ('h+', 'h+'), ('h+/h-', 'h+/h-'), ('h?', 'h?'), ('h90', 'h90')], max_length=20, verbose_name='mating type'),
        ),
        migrations.AlterField(
            model_name='scpombestrain',
            name='mating_type',
            field=models.CharField(blank=True, choices=[('h-', 'h-'), ('h+', 'h+'), ('h+/h-', 'h+/h-'), ('h?', 'h?'), ('h90', 'h90')], max_length=20, verbose_name='mating type'),
        ),
    ]
