# Generated by Django 2.2.7 on 2020-03-17 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection_management', '0004_auto_20200317_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalscpombestrain',
            name='box_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='box number'),
        ),
        migrations.AlterField(
            model_name='scpombestrain',
            name='box_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='box number'),
        ),
    ]
