# Generated by Django 2.2.9 on 2020-06-04 12:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('collection_management', '0005_auto_20200317_1401'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaloligo',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='historicaloligo',
            name='length',
        ),
        migrations.RemoveField(
            model_name='historicaloligo',
            name='restriction_site',
        ),
        migrations.RemoveField(
            model_name='oligo',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='oligo',
            name='length',
        ),
        migrations.RemoveField(
            model_name='oligo',
            name='restriction_site',
        ),
        migrations.AddField(
            model_name='historicaloligo',
            name='location',
            field=models.CharField(blank=True, max_length=255, verbose_name='location'),
        ),
        migrations.AddField(
            model_name='historicaloligo',
            name='order_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='ordered_date'),
        ),
        migrations.AddField(
            model_name='historicaloligo',
            name='ordered_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicaloligo',
            name='purification',
            field=models.CharField(blank=True, choices=[('desalting', 'desalting'), ('HPLC', 'HPLC'), ('PAGE', 'PAGE'), ('RNase', 'RNase')], max_length=20, verbose_name='purification'),
        ),
        migrations.AddField(
            model_name='historicaloligo',
            name='scale',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='scale (nanomolar)'),
        ),
        migrations.AddField(
            model_name='historicaloligo',
            name='synonym',
            field=models.CharField(blank=True, max_length=255, verbose_name='synonym'),
        ),
        migrations.AddField(
            model_name='oligo',
            name='location',
            field=models.CharField(blank=True, max_length=255, verbose_name='location'),
        ),
        migrations.AddField(
            model_name='oligo',
            name='order_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='ordered_date'),
        ),
        migrations.AddField(
            model_name='oligo',
            name='ordered_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='oligo',
            name='purification',
            field=models.CharField(blank=True, choices=[('desalting', 'desalting'), ('HPLC', 'HPLC'), ('PAGE', 'PAGE'), ('RNase', 'RNase')], max_length=20, verbose_name='purification'),
        ),
        migrations.AddField(
            model_name='oligo',
            name='scale',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='scale (nanomolar)'),
        ),
        migrations.AddField(
            model_name='oligo',
            name='synonym',
            field=models.CharField(blank=True, max_length=255, verbose_name='synonym'),
        ),
    ]
