# Generated by Django 2.2.9 on 2020-06-04 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection_management', '0006_auto_20200604_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaloligo',
            name='order_date',
            field=models.DateField(blank=True, null=True, verbose_name='ordered_date'),
        ),
        migrations.AlterField(
            model_name='historicaloligo',
            name='ordered_by',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ordered_by'),
        ),
        migrations.AlterField(
            model_name='historicaloligo',
            name='purification',
            field=models.CharField(blank=True, choices=[('Desalting', 'Desalting'), ('HPLC', 'HPLC'), ('PAGE', 'PAGE'), ('RNase', 'RNase')], max_length=20, verbose_name='purification'),
        ),
        migrations.AlterField(
            model_name='oligo',
            name='order_date',
            field=models.DateField(blank=True, null=True, verbose_name='ordered_date'),
        ),
        migrations.AlterField(
            model_name='oligo',
            name='ordered_by',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ordered_by'),
        ),
        migrations.AlterField(
            model_name='oligo',
            name='purification',
            field=models.CharField(blank=True, choices=[('Desalting', 'Desalting'), ('HPLC', 'HPLC'), ('PAGE', 'PAGE'), ('RNase', 'RNase')], max_length=20, verbose_name='purification'),
        ),
    ]
