# Generated by Django 2.2.9 on 2020-06-10 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection_management', '0007_auto_20200604_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaloligo',
            name='sequence',
            field=models.CharField(max_length=255, verbose_name='sequence'),
        ),
        migrations.AlterField(
            model_name='oligo',
            name='sequence',
            field=models.CharField(max_length=255, verbose_name='sequence'),
        ),
    ]
