# Generated by Django 2.2.9 on 2020-07-08 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection_management', '0008_auto_20200610_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='antibody',
            name='received_from',
            field=models.CharField(blank=True, max_length=255, verbose_name='received from'),
        ),
        migrations.AlterField(
            model_name='historicalantibody',
            name='received_from',
            field=models.CharField(blank=True, max_length=255, verbose_name='received from'),
        ),
    ]
