# Generated by Django 2.2.9 on 2020-07-09 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection_management', '0010_auto_20200708_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalscpombestrain',
            name='frozen_on',
            field=models.DateField(blank=True, default=None, verbose_name='frozen on'),
        ),
        migrations.AlterField(
            model_name='historicalscpombestrain',
            name='made_by',
            field=models.TextField(blank=True, default='', verbose_name='made by'),
        ),
        migrations.AlterField(
            model_name='scpombestrain',
            name='frozen_on',
            field=models.DateField(blank=True, default=None, verbose_name='frozen on'),
        ),
        migrations.AlterField(
            model_name='scpombestrain',
            name='made_by',
            field=models.TextField(blank=True, default='', verbose_name='made by'),
        ),
    ]
