# Generated by Django 2.2.9 on 2020-07-10 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection_management', '0012_auto_20200709_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalscpombestrain',
            name='former_name',
            field=models.CharField(blank=True, max_length=128, verbose_name='former name'),
        ),
        migrations.AlterField(
            model_name='historicalscpombestrain',
            name='strain_name',
            field=models.CharField(max_length=128, verbose_name='strain name'),
        ),
        migrations.AlterField(
            model_name='scpombestrain',
            name='former_name',
            field=models.CharField(blank=True, max_length=128, verbose_name='former name'),
        ),
        migrations.AlterField(
            model_name='scpombestrain',
            name='strain_name',
            field=models.CharField(max_length=128, verbose_name='strain name'),
        ),
    ]
