# Generated by Django 2.2.9 on 2020-07-10 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection_management', '0013_auto_20200710_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalscpombestrain',
            name='box_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='box number'),
        ),
        migrations.AlterField(
            model_name='scpombestrain',
            name='box_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='box number'),
        ),
    ]
