# Generated by Django 2.2.9 on 2020-09-24 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection_management', '0015_auto_20200924_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalscpombestrain',
            name='historical_strain',
            field=models.BooleanField(default=False, help_text='Strain does not exist in Germany', verbose_name='historical strain'),
        ),
        migrations.AlterField(
            model_name='scpombestrain',
            name='historical_strain',
            field=models.BooleanField(default=False, help_text='Strain does not exist in Germany', verbose_name='historical strain'),
        ),
    ]
