# Generated by Django 2.2.9 on 2020-11-10 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection_management', '0016_auto_20200924_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalscpombestrain',
            name='mating_type',
            field=models.CharField(blank=True, choices=[('h-', 'h-'), ('h+', 'h+'), ('h+/h-', 'h+/h-'), ('h?', 'h?'), ('h90', 'h90'), ('h+/h+', 'h+/h+')], max_length=20, verbose_name='mating type'),
        ),
        migrations.AlterField(
            model_name='scpombestrain',
            name='mating_type',
            field=models.CharField(blank=True, choices=[('h-', 'h-'), ('h+', 'h+'), ('h+/h-', 'h+/h-'), ('h?', 'h?'), ('h90', 'h90'), ('h+/h+', 'h+/h+')], max_length=20, verbose_name='mating type'),
        ),
    ]
