# Generated by Django 2.2.9 on 2020-12-03 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collection_management', '0017_auto_20201110_1103'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicaloligo',
            old_name='ordered_by_user',
            new_name='requested_by_user',
        ),
        migrations.RenameField(
            model_name='oligo',
            old_name='ordered_by_user',
            new_name='requested_by_user',
        ),
    ]
