# Generated by Django 2.2.9 on 2020-12-03 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection_management', '0019_rename_requested_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaloligo',
            name='arrival_date',
            field=models.DateField(blank=True, null=True, verbose_name='arrival_date'),
        ),
        migrations.AddField(
            model_name='historicaloligo',
            name='order_conf_num',
            field=models.CharField(blank=True, max_length=64, verbose_name='order confirmation number'),
        ),
        migrations.AddField(
            model_name='historicaloligo',
            name='order_date',
            field=models.DateField(blank=True, null=True, verbose_name='ordered_date'),
        ),
        migrations.AddField(
            model_name='historicaloligo',
            name='ordered',
            field=models.BooleanField(default=False, verbose_name='ordered?'),
        ),
        migrations.AddField(
            model_name='oligo',
            name='arrival_date',
            field=models.DateField(blank=True, null=True, verbose_name='arrival_date'),
        ),
        migrations.AddField(
            model_name='oligo',
            name='order_conf_num',
            field=models.CharField(blank=True, max_length=64, verbose_name='order confirmation number'),
        ),
        migrations.AddField(
            model_name='oligo',
            name='order_date',
            field=models.DateField(blank=True, null=True, verbose_name='ordered_date'),
        ),
        migrations.AddField(
            model_name='oligo',
            name='ordered',
            field=models.BooleanField(default=False, verbose_name='ordered?'),
        ),
        migrations.AlterField(
            model_name='historicaloligo',
            name='requested_date',
            field=models.DateField(blank=True, null=True, verbose_name='requested_date'),
        ),
        migrations.AlterField(
            model_name='oligo',
            name='requested_date',
            field=models.DateField(blank=True, null=True, verbose_name='requested_date'),
        ),
    ]
