# Generated by Django 2.2.13 on 2021-02-26 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection_management', '0021_auto_20201203_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaloligo',
            name='status',
            field=models.CharField(choices=[('unsubmitted', 'unsubmitted'), ('submitted', 'submitted'), ('approved', 'approved'), ('arranged', 'arranged'), ('delivered', 'delivered')], default='submitted', max_length=255, verbose_name='status'),
        ),
        migrations.AddField(
            model_name='oligo',
            name='status',
            field=models.CharField(choices=[('unsubmitted', 'unsubmitted'), ('submitted', 'submitted'), ('approved', 'approved'), ('arranged', 'arranged'), ('delivered', 'delivered')], default='submitted', max_length=255, verbose_name='status'),
        ),
    ]
