# Generated by Django 2.2.13 on 2021-03-02 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collection_management', '0023_auto_20210226_1637'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaloligo',
            name='approval_by_pi_date_time',
        ),
        migrations.RemoveField(
            model_name='historicaloligo',
            name='arrival_date',
        ),
        migrations.RemoveField(
            model_name='historicaloligo',
            name='created_approval_by_pi',
        ),
        migrations.RemoveField(
            model_name='historicaloligo',
            name='created_date_time',
        ),
        migrations.RemoveField(
            model_name='historicaloligo',
            name='last_changed_approval_by_pi',
        ),
        migrations.RemoveField(
            model_name='historicaloligo',
            name='order_date',
        ),
        migrations.RemoveField(
            model_name='historicaloligo',
            name='ordered',
        ),
        migrations.RemoveField(
            model_name='historicaloligo',
            name='requested_by_user',
        ),
        migrations.RemoveField(
            model_name='historicaloligo',
            name='requested_date',
        ),
        migrations.RemoveField(
            model_name='oligo',
            name='approval_by_pi_date_time',
        ),
        migrations.RemoveField(
            model_name='oligo',
            name='arrival_date',
        ),
        migrations.RemoveField(
            model_name='oligo',
            name='created_approval_by_pi',
        ),
        migrations.RemoveField(
            model_name='oligo',
            name='created_date_time',
        ),
        migrations.RemoveField(
            model_name='oligo',
            name='last_changed_approval_by_pi',
        ),
        migrations.RemoveField(
            model_name='oligo',
            name='order_date',
        ),
        migrations.RemoveField(
            model_name='oligo',
            name='ordered',
        ),
        migrations.RemoveField(
            model_name='oligo',
            name='requested_by_user',
        ),
        migrations.RemoveField(
            model_name='oligo',
            name='requested_date',
        ),
    ]
