# Generated by Django 2.2.13 on 2021-03-02 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection_management', '0024_auto_20210302_1343'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaloligo',
            name='approval_email',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='oligo',
            name='approval_email',
            field=models.BooleanField(default=False),
        ),
    ]
