# Generated by Django 2.2.13 on 2021-03-09 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection_management', '0025_auto_20210302_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaloligo',
            name='gene',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='gene'),
        ),
        migrations.AlterField(
            model_name='historicaloligo',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='location'),
        ),
        migrations.AlterField(
            model_name='historicaloligo',
            name='order_conf_num',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='order confirmation number'),
        ),
        migrations.AlterField(
            model_name='historicaloligo',
            name='synonym',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='synonym'),
        ),
        migrations.AlterField(
            model_name='historicaloligo',
            name='us_e',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='use'),
        ),
        migrations.AlterField(
            model_name='oligo',
            name='gene',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='gene'),
        ),
        migrations.AlterField(
            model_name='oligo',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='location'),
        ),
        migrations.AlterField(
            model_name='oligo',
            name='order_conf_num',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='order confirmation number'),
        ),
        migrations.AlterField(
            model_name='oligo',
            name='synonym',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='synonym'),
        ),
        migrations.AlterField(
            model_name='oligo',
            name='us_e',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='use'),
        ),
    ]
