# Generated by Django 2.2.13 on 2021-03-10 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection_management', '0026_auto_20210309_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaloligo',
            name='delivery_notification',
            field=models.BooleanField(default=True, verbose_name='Delivery notification?'),
        ),
        migrations.AlterField(
            model_name='oligo',
            name='delivery_notification',
            field=models.BooleanField(default=True, verbose_name='Delivery notification?'),
        ),
    ]
