# Generated by Django 2.2.13 on 2021-03-11 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection_management', '0027_auto_20210310_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaloligo',
            name='status',
            field=models.CharField(choices=[('unsubmitted', 'unsubmitted'), ('submitted', 'submitted'), ('approved', 'approved'), ('arranged', 'arranged'), ('delivered', 'delivered'), ('cancelled', 'cancelled')], default='submitted', max_length=255, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='oligo',
            name='status',
            field=models.CharField(choices=[('unsubmitted', 'unsubmitted'), ('submitted', 'submitted'), ('approved', 'approved'), ('arranged', 'arranged'), ('delivered', 'delivered'), ('cancelled', 'cancelled')], default='submitted', max_length=255, verbose_name='status'),
        ),
    ]
