# Generated by Django 2.2.18 on 2021-04-13 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection_management', '0028_auto_20210311_1029'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalscpombestrain',
            name='isolates',
            field=models.CharField(blank=True, help_text='Information on isolates A,B,C,D, etc.', max_length=255, verbose_name='Isolates'),
        ),
        migrations.AddField(
            model_name='scpombestrain',
            name='isolates',
            field=models.CharField(blank=True, help_text='Information on isolates A,B,C,D, etc.', max_length=255, verbose_name='Isolates'),
        ),
    ]
