# Generated by Django 2.2.18 on 2021-04-15 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection_management', '0029_auto_20210413_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalscpombestrain',
            name='comment',
            field=models.TextField(blank=True, verbose_name='comments'),
        ),
        migrations.AlterField(
            model_name='historicalscpombestrain',
            name='made_by',
            field=models.CharField(blank=True, max_length=255, verbose_name='made by'),
        ),
        migrations.AlterField(
            model_name='scpombestrain',
            name='comment',
            field=models.TextField(blank=True, verbose_name='comments'),
        ),
        migrations.AlterField(
            model_name='scpombestrain',
            name='made_by',
            field=models.CharField(blank=True, max_length=255, verbose_name='made by'),
        ),
    ]
