# Generated by Django 2.2.7 on 2020-01-27 15:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import order_management.models
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CostUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Name')),
                ('description', models.CharField(max_length=255, unique=True, verbose_name='Description')),
                ('status', models.BooleanField(default=False, help_text="Check it, if you want to HIDE this cost unit from the 'Add new order' form", verbose_name='deactivate?')),
            ],
            options={
                'verbose_name': 'cost unit',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='name')),
                ('status', models.BooleanField(default=False, help_text="Check it, if you want to HIDE this location from the 'Add new order' form ", verbose_name='deactivate?')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MsdsForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.FileField(help_text='max. 2 MB', unique=True, upload_to='order_management/msdsform/', verbose_name='file name')),
                ('created_date_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='created')),
                ('last_changed_date_time', models.DateTimeField(auto_now=True, null=True, verbose_name='last changed')),
            ],
            options={
                'verbose_name': 'MSDS form',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier', models.CharField(max_length=255, verbose_name='supplier')),
                ('supplier_part_no', models.CharField(max_length=255, verbose_name='supplier Part-No')),
                ('internal_order_no', models.CharField(blank=True, max_length=255, verbose_name='internal order number')),
                ('part_description', models.CharField(max_length=255, verbose_name='part description')),
                ('quantity', models.CharField(max_length=255, verbose_name='quantity')),
                ('price', models.CharField(blank=True, max_length=255, verbose_name='price')),
                ('status', models.CharField(choices=[('submitted', 'submitted'), ('open', 'open'), ('arranged', 'arranged'), ('delivered', 'delivered'), ('cancelled', 'cancelled'), ('used up', 'used up')], default='submitted', max_length=255, verbose_name='status')),
                ('urgent', models.BooleanField(default=False, verbose_name='is this an urgent order?')),
                ('delivery_alert', models.BooleanField(default=False, verbose_name='delivery notification?')),
                ('sent_email', models.BooleanField(default=False, null=True)),
                ('comment', models.TextField(blank=True, verbose_name='comments')),
                ('order_manager_created_date_time', models.DateTimeField(blank=True, null=True, verbose_name='created in OrderManager')),
                ('delivered_date', models.DateField(blank=True, default=None, null=True, verbose_name='delivered')),
                ('url', models.URLField(blank=True, max_length=400, verbose_name='URL')),
                ('cas_number', models.CharField(blank=True, max_length=255, verbose_name='CAS number')),
                ('ghs_pictogram', models.CharField(blank=True, max_length=255, verbose_name='GHS pictogram')),
                ('hazard_level_pregnancy', models.CharField(blank=True, choices=[('none', 'none'), ('yellow', 'yellow'), ('red', 'red')], default='none', max_length=255, verbose_name='Hazard level for pregnancy')),
                ('created_date_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='created')),
                ('last_changed_date_time', models.DateTimeField(auto_now=True, null=True, verbose_name='last changed')),
                ('created_approval_by_pi', models.BooleanField(default=False, null=True)),
                ('cost_unit', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='order_management.CostUnit')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='order_management.Location')),
                ('msds_form', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='order_management.MsdsForm')),
            ],
            options={
                'verbose_name': 'order',
            },
            bases=(models.Model, order_management.models.SaveWithoutHistoricalRecord),
        ),
        migrations.CreateModel(
            name='OrderExtraDoc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.FileField(help_text='max. 2 MB', upload_to='temp/', verbose_name='file name')),
                ('description', models.CharField(max_length=255, verbose_name='description')),
                ('created_date_time', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('last_changed_date_time', models.DateTimeField(auto_now=True, verbose_name='last changed')),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='order_management.Order')),
            ],
            options={
                'verbose_name': 'order extra document',
            },
        ),
        migrations.CreateModel(
            name='HistoricalOrder',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('supplier', models.CharField(max_length=255, verbose_name='supplier')),
                ('supplier_part_no', models.CharField(max_length=255, verbose_name='supplier Part-No')),
                ('internal_order_no', models.CharField(blank=True, max_length=255, verbose_name='internal order number')),
                ('part_description', models.CharField(max_length=255, verbose_name='part description')),
                ('quantity', models.CharField(max_length=255, verbose_name='quantity')),
                ('price', models.CharField(blank=True, max_length=255, verbose_name='price')),
                ('status', models.CharField(choices=[('submitted', 'submitted'), ('open', 'open'), ('arranged', 'arranged'), ('delivered', 'delivered'), ('cancelled', 'cancelled'), ('used up', 'used up')], default='submitted', max_length=255, verbose_name='status')),
                ('urgent', models.BooleanField(default=False, verbose_name='is this an urgent order?')),
                ('delivery_alert', models.BooleanField(default=False, verbose_name='delivery notification?')),
                ('sent_email', models.BooleanField(default=False, null=True)),
                ('comment', models.TextField(blank=True, verbose_name='comments')),
                ('order_manager_created_date_time', models.DateTimeField(blank=True, null=True, verbose_name='created in OrderManager')),
                ('delivered_date', models.DateField(blank=True, default=None, null=True, verbose_name='delivered')),
                ('url', models.URLField(blank=True, max_length=400, verbose_name='URL')),
                ('cas_number', models.CharField(blank=True, max_length=255, verbose_name='CAS number')),
                ('ghs_pictogram', models.CharField(blank=True, max_length=255, verbose_name='GHS pictogram')),
                ('hazard_level_pregnancy', models.CharField(blank=True, choices=[('none', 'none'), ('yellow', 'yellow'), ('red', 'red')], default='none', max_length=255, verbose_name='Hazard level for pregnancy')),
                ('created_date_time', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='created')),
                ('last_changed_date_time', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='last changed')),
                ('created_approval_by_pi', models.BooleanField(default=False, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('cost_unit', models.ForeignKey(blank=True, db_constraint=False, default=1, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='order_management.CostUnit')),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='order_management.Location')),
                ('msds_form', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='order_management.MsdsForm')),
            ],
            options={
                'verbose_name': 'historical order',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
