# Generated by Django 2.2.9 on 2021-01-08 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalorder',
            name='status',
            field=models.CharField(choices=[('submitted', 'submitted'), ('approved', 'approved'), ('arranged', 'arranged'), ('delivered', 'delivered'), ('cancelled', 'cancelled')], default='submitted', max_length=255, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('submitted', 'submitted'), ('approved', 'approved'), ('arranged', 'arranged'), ('delivered', 'delivered'), ('cancelled', 'cancelled')], default='submitted', max_length=255, verbose_name='status'),
        ),
    ]
