# Generated by Django 2.2.9 on 2021-01-08 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_management', '0003_auto_20210108_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalorder',
            name='status',
            field=models.CharField(choices=[('unsubmitted', 'unsubmitted'), ('submitted', 'submitted'), ('approved', 'approved'), ('arranged', 'arranged'), ('delivered', 'delivered'), ('cancelled', 'cancelled')], default='submitted', max_length=255, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('unsubmitted', 'unsubmitted'), ('submitted', 'submitted'), ('approved', 'approved'), ('arranged', 'arranged'), ('delivered', 'delivered'), ('cancelled', 'cancelled')], default='submitted', max_length=255, verbose_name='status'),
        ),
    ]
