# Generated by Django 2.2.9 on 2021-01-11 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_management', '0004_auto_20210108_1559'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='name')),
                ('status', models.BooleanField(default=False, help_text="Check it, if you want to HIDE this supplier from the 'Add new order' form ", verbose_name='deactivate?')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
