# Generated by Django 2.2.9 on 2021-01-11 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order_management', '0005_supplieroption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalorder',
            name='cost_unit',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='order_management.CostUnit'),
        ),
        migrations.AlterField(
            model_name='historicalorder',
            name='supplier',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='order_management.SupplierOption'),
        ),
        migrations.AlterField(
            model_name='order',
            name='cost_unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='order_management.CostUnit'),
        ),
        migrations.AlterField(
            model_name='order',
            name='supplier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='order_management.SupplierOption'),
        ),
    ]
