# Generated by Django 2.2.9 on 2021-01-11 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order_management', '0006_auto_20210111_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='cost_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='order_management.CostUnit'),
        ),
        migrations.AlterField(
            model_name='order',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='order_management.Location'),
        ),
    ]
