# Generated by Django 2.2.9 on 2021-01-11 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order_management', '0007_auto_20210111_1045'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalorder',
            old_name='email_sent',
            new_name='approval_email',
        ),
        migrations.RenameField(
            model_name='historicalorder',
            old_name='sent_email',
            new_name='delivery_email',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='email_sent',
            new_name='approval_email',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='sent_email',
            new_name='delivery_email',
        ),
    ]
