# Generated by Django 2.2.9 on 2021-01-14 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_management', '0008_auto_20210111_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalorder',
            name='supplier_part_no',
            field=models.CharField(max_length=500, verbose_name='supplier Part-No'),
        ),
        migrations.AlterField(
            model_name='order',
            name='supplier_part_no',
            field=models.CharField(max_length=500, verbose_name='supplier Part-No'),
        ),
    ]
