# Generated by Django 2.2.9 on 2021-01-14 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_management', '0009_auto_20210114_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalorder',
            name='part_description',
            field=models.TextField(verbose_name='part description'),
        ),
        migrations.AlterField(
            model_name='historicalorder',
            name='supplier_part_no',
            field=models.CharField(max_length=255, verbose_name='supplier Part-No'),
        ),
        migrations.AlterField(
            model_name='order',
            name='part_description',
            field=models.TextField(verbose_name='part description'),
        ),
        migrations.AlterField(
            model_name='order',
            name='supplier_part_no',
            field=models.CharField(max_length=255, verbose_name='supplier Part-No'),
        ),
    ]
