# Generated by Django 2.2.9 on 2021-01-15 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_management', '0010_auto_20210114_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalorder',
            name='cloned',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='cloned',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
