# Generated by Django 2.2.9 on 2021-02-05 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_management', '0012_auto_20210205_1442'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalorder',
            name='location',
        ),
        migrations.RemoveField(
            model_name='order',
            name='location',
        ),
        migrations.AddField(
            model_name='historicalorder',
            name='backup_location',
            field=models.CharField(blank=True, max_length=255, verbose_name='backup location'),
        ),
        migrations.AddField(
            model_name='historicalorder',
            name='primary_location',
            field=models.CharField(blank=True, help_text="please update with item's location after it arrives", max_length=255, verbose_name='primary location'),
        ),
        migrations.AddField(
            model_name='order',
            name='backup_location',
            field=models.CharField(blank=True, max_length=255, verbose_name='backup location'),
        ),
        migrations.AddField(
            model_name='order',
            name='primary_location',
            field=models.CharField(blank=True, help_text="please update with item's location after it arrives", max_length=255, verbose_name='primary location'),
        ),
        migrations.DeleteModel(
            name='Location',
        ),
    ]
