# Generated by Django 2.2.9 on 2021-02-05 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_management', '0014_auto_20210205_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalorder',
            name='part_description',
            field=models.TextField(help_text='Please include units that correspond to the quantity', verbose_name='part description'),
        ),
        migrations.AlterField(
            model_name='order',
            name='part_description',
            field=models.TextField(help_text='Please include units that correspond to the quantity', verbose_name='part description'),
        ),
    ]
