# Generated by Django 2.2.9 on 2021-02-05 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_management', '0015_auto_20210205_1507'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalorder',
            name='part_name',
            field=models.CharField(max_length=255, null=True, verbose_name='part name'),
        ),
        migrations.AddField(
            model_name='order',
            name='part_name',
            field=models.CharField(max_length=255, null=True, verbose_name='part name'),
        ),
    ]
