# Generated by Django 2.2.9 on 2021-02-05 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_management', '0016_auto_20210205_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalorder',
            name='price_vat',
            field=models.FloatField(blank=True, null=True, verbose_name='price (VAT-inclusive)'),
        ),
        migrations.AddField(
            model_name='order',
            name='price_vat',
            field=models.FloatField(blank=True, null=True, verbose_name='price (VAT-inclusive)'),
        ),
        migrations.AlterField(
            model_name='historicalorder',
            name='price',
            field=models.FloatField(blank=True, null=True, verbose_name='price (VAT-exclusive)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='price',
            field=models.FloatField(blank=True, null=True, verbose_name='price (VAT-exclusive)'),
        ),
    ]
