# Generated by Django 2.2.9 on 2021-02-05 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_management', '0017_auto_20210205_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalorder',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='price (VAT-exclusive)'),
        ),
        migrations.AlterField(
            model_name='historicalorder',
            name='price_vat',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='price (VAT-inclusive)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='price (VAT-exclusive)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='price_vat',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='price (VAT-inclusive)'),
        ),
    ]
