# Generated by Django 2.2.9 on 2021-02-05 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_management', '0018_auto_20210205_1605'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalorder',
            name='part_category',
            field=models.CharField(choices=[('Animal Care', 'Animal Care'), ('Antibodies', 'Antibodies'), ('Cells', 'Cells'), ('Chemicals', 'Chemicals'), ('Consumables', 'Consumables'), ('Furniture', 'Furniture'), ('Glassware', 'Glassware'), ('IT', 'IT'), ('Lab Equipment', 'Lab Equipment'), ('Office Supplies', 'Office Supplies'), ('Radioactivity', 'Radioactivity')], max_length=255, null=True, verbose_name='Item Category'),
        ),
        migrations.AddField(
            model_name='order',
            name='part_category',
            field=models.CharField(choices=[('Animal Care', 'Animal Care'), ('Antibodies', 'Antibodies'), ('Cells', 'Cells'), ('Chemicals', 'Chemicals'), ('Consumables', 'Consumables'), ('Furniture', 'Furniture'), ('Glassware', 'Glassware'), ('IT', 'IT'), ('Lab Equipment', 'Lab Equipment'), ('Office Supplies', 'Office Supplies'), ('Radioactivity', 'Radioactivity')], max_length=255, null=True, verbose_name='Item Category'),
        ),
    ]
