# Generated by Django 2.2.9 on 2021-02-08 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_management', '0019_auto_20210205_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalorder',
            name='template',
            field=models.BooleanField(default=False, verbose_name='Template Order'),
        ),
        migrations.AddField(
            model_name='order',
            name='template',
            field=models.BooleanField(default=False, verbose_name='Template Order'),
        ),
    ]
