# Generated by Django 2.2.13 on 2021-02-16 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_management', '0020_auto_20210208_1004'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalorder',
            name='urgent_email',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='urgent_email',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
