# Generated by Django 2.2.13 on 2021-02-16 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_management', '0021_auto_20210216_1428'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalorder',
            name='template',
        ),
        migrations.RemoveField(
            model_name='order',
            name='template',
        ),
        migrations.AddField(
            model_name='historicalorder',
            name='reorderable',
            field=models.BooleanField(default=True, verbose_name='Reorderable'),
        ),
        migrations.AddField(
            model_name='order',
            name='reorderable',
            field=models.BooleanField(default=True, verbose_name='Reorderable'),
        ),
    ]
