# Generated by Django 2.2.13 on 2021-02-16 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_management', '0022_auto_20210216_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalorder',
            name='part_category',
            field=models.CharField(choices=[('Animal Care', 'Animal Care'), ('Antibodies', 'Antibodies'), ('Cells', 'Cells'), ('Chemicals', 'Chemicals'), ('Consumables', 'Consumables'), ('Enzymes', 'Enzymes'), ('Furniture', 'Furniture'), ('Glassware', 'Glassware'), ('IT', 'IT'), ('Lab Equipment', 'Lab Equipment'), ('Office Supplies', 'Office Supplies'), ('Radioactivity', 'Radioactivity')], max_length=255, verbose_name='Item Category'),
        ),
        migrations.AlterField(
            model_name='order',
            name='part_category',
            field=models.CharField(choices=[('Animal Care', 'Animal Care'), ('Antibodies', 'Antibodies'), ('Cells', 'Cells'), ('Chemicals', 'Chemicals'), ('Consumables', 'Consumables'), ('Enzymes', 'Enzymes'), ('Furniture', 'Furniture'), ('Glassware', 'Glassware'), ('IT', 'IT'), ('Lab Equipment', 'Lab Equipment'), ('Office Supplies', 'Office Supplies'), ('Radioactivity', 'Radioactivity')], max_length=255, verbose_name='Item Category'),
        ),
    ]
