# Generated by Django 2.2.13 on 2021-02-16 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_management', '0023_auto_20210216_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalorder',
            name='quantity',
            field=models.IntegerField(null=True, verbose_name='quantity'),
        ),
        migrations.AlterField(
            model_name='order',
            name='quantity',
            field=models.IntegerField(null=True, verbose_name='quantity'),
        ),
    ]
