# Generated by Django 2.2.13 on 2021-02-16 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_management', '0024_auto_20210216_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalorder',
            name='url',
            field=models.URLField(blank=True, max_length=1000, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='order',
            name='url',
            field=models.URLField(blank=True, max_length=1000, verbose_name='URL'),
        ),
    ]
