# Generated by Django 2.2.13 on 2021-02-24 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_management', '0025_auto_20210216_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalorder',
            name='supplier_order_number',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Supplier Order Number'),
        ),
        migrations.AddField(
            model_name='order',
            name='supplier_order_number',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Supplier Order Number'),
        ),
    ]
