# Generated by Django 2.2.13 on 2021-03-10 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_management', '0026_auto_20210224_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalorder',
            name='delivery_alert',
            field=models.BooleanField(default=True, verbose_name='delivery notification?'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_alert',
            field=models.BooleanField(default=True, verbose_name='delivery notification?'),
        ),
    ]
