# Generated by Django 2.2.18 on 2021-04-09 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_management', '0027_auto_20210310_1633'),
    ]

    operations = [
        migrations.CreateModel(
            name='GHSCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=255, unique=True, verbose_name='code')),
                ('description', models.TextField(verbose_name='description')),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.RemoveField(
            model_name='historicalorder',
            name='ghs_pictogram',
        ),
        migrations.RemoveField(
            model_name='order',
            name='ghs_pictogram',
        ),
        migrations.AddField(
            model_name='order',
            name='ghs_codes',
            field=models.ManyToManyField(blank=True, related_name='order_ghs_codes', to='order_management.GHSCode'),
        ),
    ]
