# Generated by Django 2.2.18 on 2021-04-09 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_management', '0028_auto_20210409_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalorder',
            name='history_ghs_codes',
            field=models.TextField(blank=True, verbose_name='ghs codes'),
        ),
        migrations.AddField(
            model_name='order',
            name='history_ghs_codes',
            field=models.TextField(blank=True, verbose_name='ghs codes'),
        ),
    ]
