# Generated by Django 2.2.18 on 2021-04-06 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('record_approval', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recordtobeapproved',
            name='edited',
        ),
        migrations.RemoveField(
            model_name='recordtobeapproved',
            name='message',
        ),
        migrations.RemoveField(
            model_name='recordtobeapproved',
            name='message_date_time',
        ),
    ]
