# Generated by Django 2.2.18 on 2021-04-07 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record_approval', '0002_auto_20210406_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='recordtobeapproved',
            name='last_changed_date_time',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='last changed'),
        ),
    ]
